### ISSUE TITLE
Cmd key bindings (for undo/ redo) not working on non-MacOS systems

### ISSUE THREAD

**Issue by Lissy93** [dylanonelson/sn-scratch-editor#11]
Great editor, it's really intuitive to use :)

But one thing I cannot seem to get working is undo/ redo. The docs say it's `cmd + z`, I'm on a Windows system, and `Ctrl + z` doesn't seem to translate. The same happens with Bold, Italics, Monospace and all the other features that use the `cmd` key only. This happens on both the web app, and desktop app on Windows and Arch Linux. Maybe it's just my specific system being stupid, or is there a different key I should be using, rather than `Ctrl`?

Thanks very much,
Alicia

**Comment by dylanonelson** [comment]
Hey Alicia, thanks for opening an issue! I am so sorry I did not see this earlier. I thought I had email notifications turned on for this repo but I never got an email about this issue.

I use a Mac and I’m afraid the way I coded the hotkeys initially was Mac-centric. I just pushed a fix for this so that any hotkey that uses `cmd` will also work with `ctrl`.

**Comment by Lissy93** [comment]
Awesome, thanks for the fix, and keep up the great work :)
