### ISSUE TITLE
Remove the scrollbar below toolbar.

### ISSUE THREAD

**Issue by gaganyadav80** [dylanonelson/sn-scratch-editor#14]
The scrollbar below the formatting toolbar does not look good especially on Desktop.

![Screenshot from 2021-05-09 15-14-36](https://user-images.githubusercontent.com/47142137/117567299-5a0b1680-b0d9-11eb-8a51-ba2bc5c2bc4a.png)

**Comment by dylanonelson** [comment]
Hey, thanks for the issue. Unfortunately the way that scrollbars render is largely dependent on the system you use and the type of input device you have connected, and I can’t get rid of the scrollbar in all cases without completely changing the way the toolbar works. On my system, for example, you can make the scrollbars go away by using a trackpad instead of a mouse.

I agree the scrollbars are ugly, however, so I’ll think about whether there's another way to lay out the toolbar that would sidestep the problem.

I’m going to close this for now since it is largely out of my control, but I’m open to suggestions on how to improve it.
