### ISSUE TITLE
General text corruption on iOS

### ISSUE THREAD

**Issue by BionicBison05** [dylanonelson/sn-scratch-editor#31]
![IMG_7626](https://user-images.githubusercontent.com/93722725/149645726-5d340a35-d06d-4ecc-8ac4-313946dbd119.jpeg)
These are simply empty lines where the enter key was used. These should be blank like they are on desktop.

**Comment by BionicBison05** [comment]
https://user-images.githubusercontent.com/93722725/149669768-9b514fe6-2541-4f5f-9391-2cdf44d8cb1a.MOV

Apostrophes turn into unreadable junk

**Comment by dylanonelson** [comment]
Hey, thanks for opening an issue! I can reproduce this. I’m not sure what’s causing it, but I will take a look this week.

**Comment by dylanonelson** [comment]
Quick update on these issues: I’ve spent quite a while debugging and so far I’m not having much luck. The problem seems to have to do with the encoding of the editor, but I can’t figure out why it would be in anything other than utf-8. It’s hard to debug because so far, I can’t reproduce it outside of the iOS app. I will keep digging.

**Comment by dylanonelson** [comment]
Hey, I forgot to update this issue, but I believe I wound up pushing a fix for it around the time of my last comment. I can no longer reproduce either issue in the SN app on my iPad. Definitely let me know and reopen if you see something different.
