### ISSUE TITLE
further iOS improvements: Taskbar, Bold, Italic, <>

### ISSUE THREAD

**Issue by Penguinjumper** [dylanonelson/sn-scratch-editor#9]
Thanks again for the help with the checkbox issue, scratch is great!

I found out a few things playing around with my new favorite editor and I'll try to describe them as good as possible:

System: iOS / iPadOS 14.3
Devices: iphone XS and iPad Mini 5

**1. Taskbar:** 
Not sure if this is the right word, but the bar in the top, from where we can choose our formatting options like TT, Checkboxes, Code etc.
Issue: When typing a longer note, the bar does not stay at the top end of the screen. Instead, after a bit of scrolling it scrolls up and is no longer reachable. 
Workaround: Scroll back up all the way to the top, where it can then be found.
Expected behaviour: Stay at top of screen, to enable quick changes of format.

**2. Bold, Italic, <>**
Issue: Those quick format options only work for one character, then it goes back to default.
Example: 
I want to write 
> " **This is** _nice_ "

Instead I write

>  " **T** his is _n_ ice " (ignore extra spaces, they are for formatting on Github)

This also applies to the quick formatting options provided on the iPad's Keyboard (right of the autocorrect suggestions), which also feature bold and italic.

**3. Code**
For the "mark as Code" feature: I could not stop marking as code.
Workaround: Before marking something as code, press Enter twice, then go back to where you want the code, so you can afterwards select the lines below the code and continue typing normally.

I hope this will help with overall usability and thanks again for the great work.

**Comment by dylanonelson** [comment]
Thanks for the bug reports! I’ve pushed out fixes for issues 2 and 3. Issue number 2 is self explanatory. For number 3, you should now be able to click in an area right below the note; if the last bit of text is a code block, it will insert a new paragraph at the end and put your cursor there, but otherwise it will simply put your cursor at the existing selection at the end.

Don’t hesitate to open a new issue or respond here if you see anything amiss.

I will look into issue number 1, with the fixed position toolbar, and hopefully push out a fix soon.

**Comment by dylanonelson** [comment]
I was finally able to track down a fix for the toolbar position on iOS, which I just pushed out. Closing this issue.
